graph [
comment "Automatically generated by Graphing tool"
directed  1
id  1
label "To be more meaningful later....
"node [
id 1
label "30_29_NODE_5_length_418_cov_2.504785"
defaultAtrribute   1
]
node [
id 2
label "30_29_NODE_5_length_418_cov_2.504785_R"
defaultAtrribute   1
]
node [
id 3
label "30_27_NODE_3_length_371_cov_4.929919"
defaultAtrribute   1
]
node [
id 4
label "30_27_NODE_3_length_371_cov_4.929919_R"
defaultAtrribute   1
]

]
